### ISSUE TITLE
崩溃了

### ISSUE THREAD

**Issue by Campanulata** [HsOjo/UnlockerX#1]
[Info] Thu Nov 28 20:41:52 2019 app_init
	 version: 1.2.4 {
    "System Version": "macOS 10.15.1 (19B88)",
    "Kernel Version": "Darwin 19.0.0",
    "Boot Volume": "Mac mini",
    "Boot Mode": "Normal",
    "Computer Name": "TYLORGAN-MB1",
    "User Name": "tylor (tylor)",
    "Secure Virtual Memory": "Enabled",
    "System Integrity Protection": "Disabled",
    "Time since boot": "7:29"
}
[Info] Thu Nov 28 20:41:52 2019 app_shell
	 {
    "shell_class": "Py2App",
    "runtime_dir": "/Applications/UnlockerX.app/Contents/Resources",
    "app_path": "/Applications/UnlockerX.app"
}
[Info] Thu Nov 28 20:41:52 2019 config_load
	 {
    "bluetooth_refresh_rate": 1,
    "device_address": "",
    "disconnect_lock_delay": 10,
    "event_connect_status_changed": "",
    "event_lid_status_changed": "",
    "event_lock_status_changed": "",
    "event_signal_weak": "",
    "language": "cn",
    "password": "[protector]",
    "signal_value_visible_on_icon": false,
    "use_screen_saver_replace_lock": true,
    "weak_signal_lock_delay": 6,
    "weak_signal_value": -80,
    "welcome": false
}
[Warning] Thu Nov 28 20:41:52 2019 check_update
	 Traceback (most recent call last):
  File "app/base/application.pyc", line 269, in check_update
  File "app/util/github.pyc", line 74, in get_latest_release
  File "requests/api.pyc", line 75, in get
  File "requests/api.pyc", line 60, in request
  File "requests/sessions.pyc", line 533, in request
  File "requests/sessions.pyc", line 646, in send
  File "requests/adapters.pyc", line 416, in send
  File "requests/adapters.pyc", line 228, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /Applications/UnlockerX.app/Contents/Resources/lib/python37.zip/certifi/cacert.pem

[AppleScript] Thu Nov 28 20:41:52 2019 exec
	 {
    "code": "tell application \"System Events\" to keystroke key code 63 using {}",
    "timeout": null,
    "stat": 0,
    "out": "",
    "err": ""
}
[AppleScript] Thu Nov 28 20:41:52 2019 exec
	 {
    "code": "choose folder with prompt \"导出日志文件\" multiple selections allowed False",
    "timeout": null,
    "stat": 0,
    "out": "alias Mac mini:Users:tylor:Downloads:\n",
    "err": ""
}

**Comment by HsOjo** [comment]
这个问题是否每次运行都触发？
