### ISSUE TITLE
Have i missed something?

### ISSUE THREAD

**Issue by nemesis911** [HsOjo/UnlockerX#2]
tools/translate/api/google.py", line 98, in _translate
    line_t = self.__translate(lang_from, lang_to, line)

and 

line 29, in __translate
    [tkk] = re.findall(r"tkk:'([\d\\.]*)'", resp.text)
ValueError: not enough values to unpack (expected 1, got 0)

im getting these errors when trying to buld the project. any way to resolve this?

**Comment by HsOjo** [comment]
The google translate module is invalidate now, you can try and use the baidu translate to build.
If you just want to run this program, go to [releases](https://github.com/HsOjo/UnlockerX/releases) page download the zip file is recommended.
