### ISSUE TITLE
蓝牙信号显示异常问题

### ISSUE THREAD

**Issue by leqq00** [HsOjo/UnlockerX#5]
![image](https://user-images.githubusercontent.com/35185509/123735546-fe3b5d80-d8d1-11eb-8178-5e3d7ad5b545.png)

**Comment by leqq00** [comment]
我这怎么都显示0  ，或者就显示设备不存在

**Comment by leqq00** [comment]
电脑：M1 mac  11.4

**Comment by HsOjo** [comment]
正常现象。
* 0dBm = 信号极佳
* 手机系统/macOS会定期断开蓝牙连接，一段时间后会自动连接上的。
