### ISSUE TITLE
Doesn't lock the mac when bluetooth device is turned off.

### ISSUE THREAD

**Issue by santoshmanivannan** [HsOjo/UnlockerX#6]
I have bound my Bluetooth headphone to lock and unlock my mac but when I turn off the headphones, nothing happens. I've tried waiting for more than 30 minutes and still it doesn't lock. Please help.

System: Mac mini M1 - MacOS Monterey

**Comment by HsOjo** [comment]
Oops... I tried to use my AirPods lock and unlock my M1 device, But it works. So, maybe you should provide the log for me to analyze this problem.
